package dev.amazonFakeTask.model;

public enum ProductCategoryEnum {
  CLOTHING,
  FOOD,
  ELECTRONICS,
  BOOKS,
  HOME_AND_KITCHEN,
  BEAUTY_AND_PERSONAL_CARE,
  SPORTS_AND_OUTDOORS,
  TOYS_AND_GAMES,
  AUTOMOTIVE,
  HEALTH_AND_HOUSEHOLD,
  GARDEN_AND_OUTDOOR,
  PET_SUPPLIES,
  OFFICE_PRODUCTS,
  VIDEO_GAMES,
  BABY,
  TOOLS_AND_HOME_IMPROVEMENT
}
